name: gcloud
description: Configure gcloud
inputs:
  cloud_sdk_service_account_key:
    required: true
  gcp_project:
    required: true
  gcp_zone:
    required: true
  create:
    required: false
  destroy:
    required: false
  run-id:
    required: false
    default: ${{ github.context.run_id }}
runs:
  using: node12
  main: main.js