name: gcloud2
description: Configure gcloud
inputs:
  cloud_sdk_service_account_key:
    required: true
  gcp_project:
    required: true
  gcp_zone:
    required: true
  create:
    required: false
  destroy:
    required: false
  run-id:
    required: false
    default: ${{ github.run_id }}
runs:
  using: docker
  image: Dockerfile