name: Docker Build
description: Builds linkerd's docker images
inputs:
  docker-registry:
    description: The docker registry used to tag the images
    required: false
    default: cr.l5d.io/linkerd
  docker-target:
    description: The OS-arch the docker build will be targeted to
    required: false
    default: linux-amd64
  docker-push:
    description: Whether to push the built images to the registry
    required: false
    default: ''
  component:
    description: Image to build
    required: true
runs:
  using: "composite"
  steps:
    - name: Set environment variables from scripts
      shell: bash
      run: |
        . bin/_tag.sh
        echo "TAG=$(CI_FORCE_CLEAN=1 bin/root-tag)" >> $GITHUB_ENV
        echo "DOCKER_BUILDKIT_CACHE=${{ runner.temp }}/.buildx-cache" >> $GITHUB_ENV
    - name: Cache docker layers
      uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
      with:
        path: ${{ env.DOCKER_BUILDKIT_CACHE }}
        key: ${{ runner.os }}-buildx-${{ inputs.component }}-${{ env.TAG }}
        restore-keys: ${{ runner.os }}-buildx-${{ inputs.component }}-
    # TODO: guard these two with `if: inputs.docker-target == 'multi-arch'
    # when this get's fixed: https://github.com/actions/runner/issues/834
    - name: Set up QEMU
      uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@abe5d8f79a1606a2d3e218847032f3f2b1726ab0
    - name: Build docker images
      env:
        DOCKER_REGISTRY: ${{ inputs.docker-registry }}
        DOCKER_TARGET: ${{ inputs.docker-target }}
        DOCKER_PUSH: ${{ inputs.docker-push }}
      shell: bash
      run: |
        if [[ -n "$DOCKER_PUSH" ]];then
          echo "${{ secrets.DOCKER_GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.DOCKER_GHCR_USERNAME }}" --password-stdin
        fi
        bin/docker-build-${{ inputs.component }}
    - name: Prune docker layers cache
      # changes generate new images while the existing ones don't get removed
      # so we manually do that to avoid bloating the cache
      shell: bash
      run: bin/docker-cache-prune
    - name: Create artifact with CLI and image archives
      env:
        ARCHIVES: /home/runner/archives
      shell: bash
      run: |
        mkdir -p $ARCHIVES
        if [[ -n "${{ inputs.docker-push }}" ]] && [ "${{ matrix.component }}" = 'cli-bin' ];then
          # windows_static_cli_tests needs this because it can't create linux containers
          DOCKER_TARGET=windows bin/docker-pull-binaries $TAG
          cp $PWD/target/release/linkerd2-cli-$TAG-windows.exe $ARCHIVES/linkerd-windows.exe
        else
          docker save "${{ inputs.docker-registry }}/${{ inputs.component }}:$TAG" > $ARCHIVES/${{ inputs.component }}.tar
        fi
    # `with.path` values do not support environment variables yet, so an
    # absolute path is used here.
    # https://github.com/actions/upload-artifact/issues/8
    - uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074
      with:
        name: image-archives
        path: /home/runner/archives
