name: ARM

on: push

jobs:

  arm64_integration_tests:
    name: ARM64 integration tests
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    steps:
      - uses: cross-platform-actions/action@v0.6.2
        with:
          operating_system: linux
          architecture: arm64
          shell: bash
          run: |
              uname -a
              echo $SHELL
              pwd
              ls -lah
              whoami
              env | sort
