name: ARM

on: push

jobs:

  arm64_integration_tests:
    name: ARM64 integration tests
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    steps:
      - uses: uraimo/run-on-arch-action@v2
        id: runcmd
        with:
          arch: aarch64
          distro: alpine_latest
          run: |
            uname -a
            apk add docker
            whoami
            addgroup username docker
            service docker start
            docker info
