name: ARM

on: push

jobs:

  arm64_integration_tests:
    name: ARM64 integration tests
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    steps:
      - run: |
          sudo apt install -y cloud-image-utils qemu-system-arm qemu-efi
          img=ubuntu-18.04-server-cloudimg-arm64.img
          wget "https://cloud-images.ubuntu.com/releases/18.04/release/${img}"
          qemu-img resize "$img" +128G
          user_data=user-data.img
          cat >user-data <<EOF
password: asdfqwer
chpasswd: { expire: False }
ssh_pwauth: True
EOF
          cloud-localds "$user_data" user-data
          dd if=/dev/zero of=flash0.img bs=1M count=64
          dd if=/usr/share/qemu-efi/QEMU_EFI.fd of=flash0.img conv=notrunc
          dd if=/dev/zero of=flash1.img bs=1M count=64
          qemu-system-aarch64 \
            -M virt \
            -cpu cortex-a57 \
            -device rtl8139,netdev=net0 \
            -m 4096 \
            -netdev user,id=net0 \
            -nographic \
            -smp 4 \
            -drive "if=none,file=${img},id=hd0" \
            -device virtio-blk-device,drive=hd0 \
            -drive "file=${user_data},format=raw" \
            -pflash flash0.img \
            -pflash flash1.img
