name: ARM

on: push

jobs:

  arm64_integration_tests:
    name: ARM64 integration tests
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    steps:
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: alpine_latest
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)

      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
