name: KinD integration
on:
  pull_request: {}
  push:
    branches:
    - master
    tags:
    - "*"
jobs:
  docker_build:
    name: Docker build
    runs-on: ubuntu-18.04
    env:
      TAG: stable-2.7.1
    steps:
    - name: Checkout code again
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: set env
      run: |
        echo ::set-env name=LINKERD_VERSION::${TAG#"stable-"}
    - name: update version in nuspec file
      run: |
        sed -i s/$\{LINKERD_VERSION\}/$LINKERD_VERSION/g bin/win/linkerd.nuspec
        cat bin/win/linkerd.nuspec
    - name: choco pack
      # crazy-max/ghaction-chocolatey@v1.2.2
      uses: crazy-max/ghaction-chocolatey@55c9188
      with:
        args: pack bin/win/linkerd.nuspec
    - name: Create release
      id: create_release
      # softprops/action-gh-release@v1
      uses: softprops/action-gh-release@91409e7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prelease: false
        files: |
          linkerd.$LINKERD_VERSION.nupkg
