name: KinD integration
on:
  pull_request: {}
  push:
    branches:
    - master
  env:
    LINKERD_VERSION: 2.6.1
jobs:
  docker_build:
    name: Docker build
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: update version in nuspec file
      run: |
        sed -i s/$\{LINKERD_VERSION\}/${{ env.LINKERD_VERSION }}/g bin/win/linkerd.nuspec
    - name: choco pack
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: pack bin/win/linkerd.nuspec
    - name: upload nupkg file
      uses: actions/upload-artifact@v1
      with:
        name: linkerd-stable-${{ env.LINKERD_VERSION }}.nupkg
        path: linkerd.${{ env.LINKERD_VERSION }}.nupkg
