name: KinD integration
on:
  pull_request: {}
  push:
    branches:
    - master
jobs:
  docker_build:
    name: Docker build
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: lint
      # devblackops/github-action-psscriptanalyzer@v2.0.0
      uses: devblackops/github-action-psscriptanalyzer@889a059
      env:
        # https://github.com/devblackops/github-action-psscriptanalyzer/pull/3/files
        FAILONWARNING: true
      with:
        rootPath: bin/win/tools
        failOnInfos: true
