name: KinD integration
on:
  pull_request: {}
  push:
    paths-ignore:
    - '*.md'
    - '**/*.md'
    branches:
    - master
env:
  GH_ANNOTATION: true
  DOCKER_BUILDKIT: 1
jobs:
  docker_build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target: [proxy, controller, web, cni-plugin, debug, cli-bin, grafana]
    name: Docker build (${{ matrix.target }})
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Set environment variables from scripts
      run: |
        . bin/_tag.sh
        echo ::set-env name=TAG::$(CI_FORCE_CLEAN=1 bin/root-tag)
        . bin/_docker.sh
        echo ::set-env name=DOCKER_REGISTRY::$DOCKER_REGISTRY
        echo ::set-env name=DOCKER_BUILDKIT_CACHE::${{ runner.temp }}/.buildx-cache
    - name: Setup docker buildx
      # crazy-max/ghaction-docker-buildx@v3.2.0
      uses: crazy-max/ghaction-docker-buildx@552c9de
    - name: Cache docker layers
      # actions/cache@v2.0.0
      uses: actions/cache@b820478
      with:
        path: ${{ env.DOCKER_BUILDKIT_CACHE }}
        key: ${{ runner.os }}-buildx4-${{ matrix.target }}-${{ env.TAG }}
        restore-keys: |
          ${{ runner.os }}-buildx5-${{ matrix.target }}-
    - name: Build docker images
      env:
        TRACE: 1
        DOCKER_TRACE: 1
      run: |
        export PATH="`pwd`/bin:$PATH"
        bin/docker-build-${{ matrix.target }}
    - name: Create artifact with CLI and image archives
      env:
        ARCHIVES: /home/runner/archives
      run: |
        mkdir -p $ARCHIVES
        docker save "$DOCKER_REGISTRY/${{ matrix.target }}:$TAG" > $ARCHIVES/${{ matrix.target }}.tar
        # save windows cli into artifacts
        if [ '${{ matrix.target }}' == 'cli-bin' ]; then
          cp -r ./target/cli/windows/linkerd $ARCHIVES/linkerd-windows.exe
        fi
    # `with.path` values do not support environment variables yet, so an
    # absolute path is used here.
    # https://github.com/actions/upload-artifact/issues/8
    - name: Upload artifact
      # actions/upload-artifact@v1
      uses: actions/upload-artifact@3446296
      with:
        name: image-archives
        path: /home/runner/archives
  # todo: Keep in sync with `release.yml`
  windows_static_cli_tests:
    name: Static CLI tests (windows)
    runs-on: windows-latest
    needs: [docker_build]
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Try to load cached Go modules
      # actions/cache@v1.1.2
      uses: actions/cache@70655ec
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Download image archives
      # actions/download-artifact@v1
      uses: actions/download-artifact@18f0f59
      with:
        name: image-archives
    - name: Run CLI Integration tests
      run: |
        go test --failfast --mod=readonly ".\test\cli" --linkerd=$PWD\image-archives\linkerd-windows.exe --cli-tests -v
  # todo: Keep in sync with `release.yml`
  kind_integration_tests:
    strategy:
      matrix:
        integration_test: [cluster-domain, deep, external-issuer, helm-deep, helm-upgrade, uninstall, upgrade-edge, upgrade-stable]
    needs: [docker_build]
    name: Integration tests (${{ matrix.integration_test }})
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Try to load cached Go modules
      # actions/cache@v1.1.2
      uses: actions/cache@70655ec
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Set environment variables from scripts
      run: |
        . bin/_tag.sh
        echo ::set-env name=TAG::$(CI_FORCE_CLEAN=1 bin/root-tag)

        . bin/_docker.sh
        echo ::set-env name=DOCKER_REGISTRY::$DOCKER_REGISTRY
    - name: Download image archives
      # actions/download-artifact@v1
      uses: actions/download-artifact@18f0f59
      with:
        name: image-archives
    - name: Load cli-bin image into local docker images
      run: docker load < image-archives/cli-bin.tar
    - name: Install CLI
      run: |
        # Copy the CLI out of the local cli-bin container.
        container_id=$(docker create "$DOCKER_REGISTRY/cli-bin:$TAG")
        docker cp $container_id:/out/linkerd-linux "$HOME/.linkerd"

        # Validate the CLI version matches the current build tag.
        [[ "$TAG" == "$($HOME/.linkerd version --short --client)" ]]
    - name: Run integration tests
      if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork
      run: |
        bin/tests --images --name ${{ matrix.integration_test }} "$HOME/.linkerd"
