name: Build test

on:
  push:
    tags:
    - "edge-*"
    - "stable-*"

permissions:
  contents: read

env:
  GH_ANNOTATION: true
  DOCKER_REGISTRY: ghcr.io/linkerd

jobs:

  docker_build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        component:
        - policy-controller
    name: Docker build (${{ matrix.component }})
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - uses: ./.github/actions/docker-build
      with:
        docker-registry: ${{ env.DOCKER_REGISTRY }}
        docker-target: multi-arch
        docker-ghcr-username: ${{ secrets.DOCKER_GHCR_USERNAME }}
        component: ${{ matrix.component }}
