name: Policy Controller

on:
  pull_request:
    paths:
      - .github/workflows/policy_controller.yml
      - Cargo.lock
      - Cargo.toml
      - charts/linkerd-control-plane/templates/destination-rbac.yaml
      - charts/linkerd-crds/templates/policy/**
      - deny.toml
      - policy-controller/**
      - policy-test/**
      - rust-toolchain

permissions:
  contents: read

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  K3D_VERSION: v5.4.1
  PROTOC_NO_VENDOR: 1
  PROXY_INIT_VERSION: v1.5.3
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  docker-build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        component:
          - policy-controller
    name: Docker build (${{ matrix.component }})
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: ./.github/actions/docker-build
        with:
          docker-registry: ghcr.io/mateiidavid/linkerd2
          docker-target: multi-arch
          docker-push: 1
          docker-ghcr-username: ${{ secrets.DOCKER_GHCR_USERNAME }}
          docker-ghcr-pat: ${{ secrets.DOCKER_GHCR_PAT }}
          component: ${{ matrix.component }}
      # TAG is set by docker-build
      - run: echo $TAG
      - name: Create artifact with CLI and image archives
        run: |
          mkdir -p /home/runner/archives
          echo "Created archive: $(ls /home/runner/archives)"
          echo "Pulling ghcr.io/mateiidavid/linkerd2/${{ matrix.component }}:$TAG"
          docker pull "ghcr.io/mateiidavid/linkerd2/${{ matrix.component }}:$TAG"
          docker save "ghcr.io/mateiidavid/linkerd2/${{ matrix.component }}:$TAG" \
            >/home/runner/archives/${{ matrix.component }}.tar
      - name: Upload artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: image-archives
          path: /home/runner/archives

