name: Release
on:
  push:
    tags:
    - "*"
env:
  GH_ANNOTATION: true
  DOCKER_BUILDKIT: 1
jobs:
  kind_integration_tests:
    strategy:
      matrix:
        integration_test:
        - cluster-domain
        - deep
        - external-issuer
        - helm-deep
        - helm-upgrade
        - uninstall
        - upgrade-edge
        - upgrade-stable
        - cni-calico-deep
    name: Integration tests (${{ matrix.integration_test }})
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Try to load cached Go modules
      # actions/cache@v1.1.2
      uses: actions/cache@70655ec
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Set environment variables from scripts
      run: |
        TAG="$(CI_FORCE_CLEAN=1 bin/root-tag)"
        CMD="$PWD/target/release/linkerd2-cli-$TAG-linux-amd64"
        echo "::set-env name=CMD::$CMD"
        echo "::set-env name=TAG::$TAG"
    - name: Run integration tests
      run: |
        bin/docker-pull-binaries $TAG
        # Validate the CLI version matches the current build tag.
        [[ "$TAG" == "$($CMD version --short --client)" ]]
        bin/tests --images --name ${{ matrix.integration_test }} "$CMD"
