#
# This file is a mostly a concatenation of `kind_integration.yml` and
# `cloud_integration.yml`, specifically for release. Once GitHub Actions
# supports YAML anchors, we should be able to share most of the content
# between these files:
# https://github.community/t5/GitHub-Actions/Support-for-YAML-anchors/m-p/30336
#

name: Release
on:
  push:
    tags:
    - "*"
jobs:
  # todo: Keep in sync with `cloud_integration.yml`
  docker_build:
    name: Docker build
    runs-on: ubuntu-18.04
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Pull CLI binaries
      env:
        TAG: edge-20.2.2
      run : bin/docker-pull-binaries $TAG
    - name: see
      run: ls -la target/release
    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@91409e7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prelease: false
        files: |
          ./target/release/linkerd2-cli-edge-20.2.2-darwin
          ./target/release/linkerd2-cli-edge-20.2.2-darwin.sha256
          ./target/release/linkerd2-cli-edge-20.2.2-linux
          ./target/release/linkerd2-cli-edge-20.2.2-linux.sha256
          ./target/release/linkerd2-cli-edge-20.2.2-windows.exe
          ./target/release/linkerd2-cli-edge-20.2.2-windows.exe.sha256
