name: Release
on:
  push:
    tags:
    - "*"
permissions:
  contents: read
env:
  GH_ANNOTATION: true
jobs:
  docker_build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # Keep in sync with integration_tests.yaml matrix build
        target: [proxy, controller, metrics-api, web, cni-plugin, debug, cli-bin, grafana, jaeger-webhook, tap]
    name: Docker build (${{ matrix.target }})
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Set environment variables from scripts
      run: |
        . bin/_tag.sh
        echo "TAG=$(CI_FORCE_CLEAN=1 bin/root-tag)" >> $GITHUB_ENV

        . bin/_docker.sh
        echo "DOCKER_REGISTRY=ghcr.io/alpeb" >> $GITHUB_ENV
        echo "DOCKER_BUILDKIT_CACHE=${{ runner.temp }}/.buildx-cache" >> $GITHUB_ENV
    - name: Cache docker layers
      uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
      with:
        path: ${{ env.DOCKER_BUILDKIT_CACHE }}
        key: ${{ runner.os }}-buildx-${{ matrix.target }}-${{ env.TAG }}
        restore-keys: ${{ runner.os }}-buildx-${{ matrix.target }}-
    - name: Set up QEMU
      uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@abe5d8f79a1606a2d3e218847032f3f2b1726ab0
    - name: Build & Push Multi Arch Images
      env:
        DOCKER_REGISTRY: ghcr.io/alpeb
        DOCKER_TARGET: multi-arch
        DOCKER_PUSH: 1
      run: |
        echo "${{ secrets.DOCKER_GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.DOCKER_GHCR_USERNAME }}" --password-stdin
        bin/docker-build-${{ matrix.target }}
    - name: Prune docker layers cache
      # changes generate new images while the existing ones don't get removed
      # so we manually do that to avoid bloating the cache
      run: bin/docker-cache-prune
    - name: Create artifact with CLI
      # windows_static_cli_tests below needs this because it can't create linux containers
      # inside windows
      if: matrix.target == 'cli-bin'
      env:
        DOCKER_REGISTRY: ghcr.io/alpeb
        ARCHIVES: /home/runner/archives
      run: |
        bin/docker-pull-binaries $TAG
        mkdir -p $ARCHIVES
        cp -r $PWD/target/release/linkerd2-cli-$TAG-windows.exe $ARCHIVES/linkerd-windows.exe
    # `with.path` values do not support environment variables yet, so an
    # absolute path is used here.
    #
    # https://github.com/actions/upload-artifact/issues/8
    - name: Upload artifact
      if: matrix.target == 'cli-bin'
      uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074
      with:
        name: image-archives
        path: /home/runner/archives

  policy_controller_build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      matrix:
        arch: [amd64, arm64, arm]
    name: Policy controller build (${{ matrix.arch }})
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@abe5d8f79a1606a2d3e218847032f3f2b1726ab0
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - run: |
        . bin/_tag.sh
        echo "TAG=$(CI_FORCE_CLEAN=1 bin/root-tag)" >> $GITHUB_ENV
    - name: Build ${{ matrix.arch }}
      run: |
        echo "${{ secrets.DOCKER_GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.DOCKER_GHCR_USERNAME }}" --password-stdin
        docker buildx build --push ./policy-controller/ \
          -f ./policy-controller/${{ matrix.arch }}.dockerfile \
          -t ghcr.io/alpeb/policy-controller:$TAG-${{ matrix.arch }}

  policy_controller_manifest:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    needs: [policy_controller_build]
    name: Policy controller manifest
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - run: |
        . bin/_tag.sh
        echo "TAG=$(CI_FORCE_CLEAN=1 bin/root-tag)" >> $GITHUB_ENV
    - name: Create multiarch manifest
      run: |
        docker manifest create ghcr.io/alpeb/policy-controller:${TAG} \
            ghcr.io/alpeb/policy-controller:${TAG}-amd64 \
            ghcr.io/alpeb/policy-controller:${TAG}-arm64 \
            ghcr.io/alpeb/policy-controller:${TAG}-arm
    - name: Annotate multiarch manifest
      run: |
        docker manifest annotate ghcr.io/alpeb/policy-controller:$TAG \
            ghcr.io/alpeb/policy-controller:${TAG}-amd64 --os=linux --arch=amd64
        docker manifest annotate ghcr.io/alpeb/policy-controller:$TAG \
            ghcr.io/alpeb/policy-controller:${TAG}-arm64 --os=linux --arch=arm64
        docker manifest annotate ghcr.io/alpeb/policy-controller:$TAG \
            ghcr.io/alpeb/policy-controller:${TAG}-arm --os=linux --arch=arm
    - name: Push multiarch manifest
      run: |
        echo "${{ secrets.DOCKER_GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.DOCKER_GHCR_USERNAME }}" --password-stdin
        docker manifest push ghcr.io/alpeb/policy-controller:$TAG

  # todo: Keep in sync with `integration_tests.yml`
  windows_static_cli_tests:
    name: Static CLI tests (windows)
    timeout-minutes: 30
    runs-on: windows-latest
    needs: [docker_build]
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Try to load cached Go modules
      uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    - name: Download image archives
      uses: actions/download-artifact@3be87be14a055c47b01d3bd88f8fe02320a9bb60
      with:
        name: image-archives
        path: image-archives
    - name: Run CLI Integration tests
      run: go test --failfast --mod=readonly ".\test\cli" --linkerd=$PWD\image-archives\linkerd-windows.exe --cli-tests -v
  integration_tests:
    strategy:
      matrix:
        integration_test:
        - cluster-domain
        - deep
        - external-issuer
        - external-prometheus-deep
        - external-resources
        - helm-deep
        - helm-upgrade
        - uninstall
        - upgrade-edge
        - upgrade-stable
        - cni-calico-deep
    needs: [docker_build, policy_controller_manifest]
    name: Integration tests (${{ matrix.integration_test }})
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Try to load cached Go modules
      uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Set environment variables from scripts
      run: |
        TAG="$(CI_FORCE_CLEAN=1 bin/root-tag)"
        CMD="$PWD/target/release/linkerd2-cli-$TAG-linux-amd64"
        echo "CMD=$CMD" >> $GITHUB_ENV
        echo "TAG=$TAG" >> $GITHUB_ENV
    - name: Run integration tests
      env:
        DOCKER_REGISTRY: ghcr.io/alpeb
      run: |
        bin/docker-pull-binaries $TAG
        # Validate the CLI version matches the current build tag.
        [[ "$TAG" == "$($CMD version --short --client)" ]]
        bin/tests --images preload --name ${{ matrix.integration_test }} "$CMD"

  arm64_integration_tests:
    name: ARM64 integration tests
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    needs: [docker_build, policy_controller_manifest]
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Try to load cached Go modules
      uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Install linkerd CLI
      env:
        DOCKER_REGISTRY: ghcr.io/alpeb
      run: |
        TAG="$(CI_FORCE_CLEAN=1 bin/root-tag)"
        CMD="$PWD/target/release/linkerd2-cli-$TAG-linux-amd64"
        bin/docker-pull-binaries $TAG
        $CMD version --client
        # validate CLI version matches the repo
        [[ "$TAG" == "$($CMD version --short --client)" ]]
        echo "Installed Linkerd CLI version: $TAG"
        echo "CMD=$CMD" >> $GITHUB_ENV
    - name: Set KUBECONFIG environment variables
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.ARM64_KUBECONFIG }}" > $HOME/.kube/config
        echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV
        kubectl cluster-info
    - name: Run integration tests
      env:
        RUN_ARM_TEST: 1
      run: bin/tests --name deep --images preload --skip-cluster-create "$CMD"
    - name: CNI tests
      run: |
        export TAG="$($CMD version --client --short)"
        go test -cover -race -v -mod=readonly ./cni-plugin/test -integration-tests
    - name: Test cleanup
      if: ${{ always() }}
      # will fail if other steps didn't run, so ignore error
      run: bin/test-cleanup "$CMD" || true

  choco_pack:
    # only runs for stable tags. The conditionals are at each step level instead of the job level
    # otherwise the jobs below that depend on this one won't run
    name: Pack Chocolatey release
    timeout-minutes: 30
    needs: [integration_tests]
    runs-on: windows-2019
    steps:
    - name: Checkout code
      if: startsWith(github.ref, 'refs/tags/stable')
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Chocolatey - update nuspec
      if: startsWith(github.ref, 'refs/tags/stable')
      run: |
        $LINKERD_VERSION=$env:GITHUB_REF.Substring(17)
        (Get-Content bin\win\linkerd.nuspec).replace('LINKERD_VERSION', $LINKERD_VERSION) | Set-Content bin\win\linkerd.nuspec
    - name: Chocolatey - pack
      if: startsWith(github.ref, 'refs/tags/stable')
      uses: crazy-max/ghaction-chocolatey@d025252287b66c3fb7d795cc8932dec97630cd53
      with:
        args: pack bin/win/linkerd.nuspec
    - name: Chocolatey - upload package
      if: startsWith(github.ref, 'refs/tags/stable')
      uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074
      with:
        name: choco
        path: ./linkerd.*.nupkg

  gh_release:
    name: Create GH release
    timeout-minutes: 30
    if: startsWith(github.ref, 'refs/tags/stable') || startsWith(github.ref, 'refs/tags/edge')
    runs-on: ubuntu-20.04
    needs: [choco_pack]
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Set environment variables from scripts
      run: |
        . bin/_tag.sh
        . bin/_release.sh
        echo "TAG=$(CI_FORCE_CLEAN=1 bin/root-tag)" >> $GITHUB_ENV
        extract_release_notes NOTES.md
    - name: Download choco package
      if: startsWith(github.ref, 'refs/tags/stable')
      uses: actions/download-artifact@3be87be14a055c47b01d3bd88f8fe02320a9bb60
      with:
        name: choco
        path: choco
    - name: Pull CLI binaries
      env:
        DOCKER_REGISTRY: ghcr.io/alpeb
      run : |
        bin/docker-pull-binaries $TAG
        VERSION=${TAG#"stable-"}
        mv choco/linkerd.*.nupkg target/release/linkerd2-cli-stable-$VERSION.nupkg || true
    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@fb0163a75bee697a9cfec2c931801de7c7f10042
      with:
        draft: false
        prerelease: false
        body_path: NOTES.md
        files: |
          ./target/release/linkerd2-cli-*-darwin*
          ./target/release/linkerd2-cli-*-linux-*
          ./target/release/linkerd2-cli-*-windows.*
          ./target/release/linkerd2-cli-*.nupkg
