name: Release
on:
  push:
    branches:
    - master
env:
  GH_ANNOTATION: true
  LINKERD_VERSION:
jobs:
  foo:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: calculate version
      run: |
        TAG=stable-2.7.1
        echo "TAG: $TAG"
        echo ::set-env name=LINKERD_VERSION::${TAG#"stable-"}
    - name: showversion
      run: |
        echo "version: $LINKERD_VERSION"
  gh_release:
    name: Create GH release
    needs: [foo]
    runs-on: windows-2019
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Chocolatey - update nuspec
      run: |
        gci env:* | sort-object name
        (Get-Content bin\win\linkerd.nuspec).replace('LINKERD_VERSION', $env:LINKERD_VERSION) | Set-Content bin\win\linkerd.nuspec
    - name: Chocolatey - pack
      # crazy-max/ghaction-chocolatey@v1.2.2
      uses: crazy-max/ghaction-chocolatey@55c9188
      with:
        args: pack bin/win/linkerd.nuspec
    - name: Upload artifact
      # actions/upload-artifact@v1
      uses: actions/upload-artifact@3446296
      with:
        name: choco 
        path: ./linkerd.2.7.1.nupkg
