#
# This file is a mostly a concatenation of `kind_integration.yml` and
# `cloud_integration.yml`, specifically for release. Once GitHub Actions
# supports YAML anchors, we should be able to share most of the content
# between these files:
# https://github.community/t5/GitHub-Actions/Support-for-YAML-anchors/m-p/30336
#

name: Release
on:
  push:
    tags:
    - "*"
env:
  GH_ANNOTATION: true
jobs:
  # todo: Keep in sync with `cloud_integration.yml`
  gh_release:
    name: Create GH release
    if: startsWith(github.ref, 'refs/tags/stable') || startsWith(github.ref, 'refs/tags/edge')
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Set environment variables from scripts
      run: |
        . bin/_tag.sh
        . bin/_release.sh
        echo ::set-env name=TAG::$(CI_FORCE_CLEAN=1 bin/root-tag)
        extract_release_notes NOTES.md
    - name: Chocolatey - set version
      if: startsWith(github.ref, 'refs/tags/stable')
      run: |
        echo ::set-env name=LINKERD_VERSION::${TAG#"stable-"}
    - name: Chocolatey - update nuspec
      if: startsWith(github.ref, 'refs/tags/stable')
      run: |
        sed -i s/$\{LINKERD_VERSION\}/$LINKERD_VERSION/g bin/win/linkerd.nuspec
        cd bin/win
    - name: Chocolatey - pack
      if: startsWith(github.ref, 'refs/tags/stable')
      # crazy-max/ghaction-chocolatey@v1.2.2
      uses: crazy-max/ghaction-chocolatey@55c9188
      with:
        args: pack bin/win/linkerd.nuspec
    - name: Chocolatey - reset dir
      run: cd ../..
    - name: Create release
      id: create_release
      # softprops/action-gh-release@v1
      uses: softprops/action-gh-release@91409e7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: false
        body_path: NOTES.md
        files: |
          ./target/release/linkerd2-cli-*-darwin
          ./target/release/linkerd2-cli-*-darwin.sha256
          ./target/release/linkerd2-cli-*-linux
          ./target/release/linkerd2-cli-*-linux.sha256
          ./target/release/linkerd2-cli-*-windows.exe
          ./target/release/linkerd2-cli-*-windows.exe.sha256
          ./linkerd.*.nupkg
