name: Release
on:
  push:
    tags:
    - "*"
    branches:
    - master
env:
  GH_ANNOTATION: true
jobs:
  gh_release:
    name: Create GH release
    runs-on: windows-2019
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Chocolatey - update nuspec
      run: |
        $LINKERD_VERSION=$env:GITHUB_REF.Substring(17)
        (Get-Content bin\win\linkerd.nuspec).replace('LINKERD_VERSION', $LINKERD_VERSION) | Set-Content bin\win\linkerd.nuspec
    - name: Chocolatey - pack
      # crazy-max/ghaction-chocolatey@v1.2.2
      uses: crazy-max/ghaction-chocolatey@55c9188
      with:
        args: pack bin/win/linkerd.nuspec
    - name: Chocolatey - upload package
      # actions/upload-artifact@v2.01
      uses: actions/upload-artifact@97b7dac
      with:
        name: choco 
        path: ./linkerd.*.nupkg
