#
# This file is a mostly a concatenation of `kind_integration.yml` and
# `cloud_integration.yml`, specifically for release. Once GitHub Actions
# supports YAML anchors, we should be able to share most of the content
# between these files:
# https://github.community/t5/GitHub-Actions/Support-for-YAML-anchors/m-p/30336
#

name: Release
on:
  push:
    tags:
    - "*"
jobs:
  gh_release:
    name: Create GH release
    if: startsWith(github.ref, 'refs/tags/stable') || startsWith(github.ref, 'refs/tags/edge')
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set environment variables from scripts
      id: vars
      env:
        TAG: edge-20.2.3
      run: |
        . bin/_tag.sh
        . bin/_release.sh
        echo ::set-env name=TAG::$(CI_FORCE_CLEAN=1 bin/root-tag)
        FOOBAR=$(extract_release_notes)
        echo ::set-env name=NOTES::$FOOBAR
        #echo ::set-output name=NOTES::$FOOBAR
        cat $FOOBAR
    - name: Pull CLI binaries
      env:
        TAG: edge-20.2.3
      run : bin/docker-pull-binaries $TAG
    - name: test notes
      run: |
        echo $NOTES
        cat $NOTES
    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@91409e7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prelease: false
        body_path: ${{ github.env.NOTES }}
        #body_path: ${{ github.steps.vars.outputs.NOTES }}
        #body_path: NOTES.md
        files: |
          ./target/release/linkerd2-cli-*-darwin
          ./target/release/linkerd2-cli-*-darwin.sha256
          ./target/release/linkerd2-cli-*-linux
          ./target/release/linkerd2-cli-*-linux.sha256
          ./target/release/linkerd2-cli-*-windows.exe
          ./target/release/linkerd2-cli-*-windows.exe.sha256
