name: Release
on:
  push:
    branches:
    - master
env:
  GH_ANNOTATION: true
jobs:
  # todo: Keep in sync with `cloud_integration.yml`
  gh_release:
    name: Create GH release
    runs-on: windows-2019
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Pull CLI binaries
      run : bin/docker-pull-binaries stable-2.7.1
    - name: Chocolatey - set version
      run: |
        echo "::set-env name=LINKERD_VERSION::2.7.1"
    - name: Chocolatey - update nuspec
#      env:
#        LINKERD_VERSION: ${{ env.LINKERD_VERSION }}
      run: |
        gci env:* | sort-object name
        (Get-Content bin\win\linkerd.nuspec).replace('LINKERD_VERSION', $env:LINKERD_VERSION) | Set-Content bin\win\linkerd.nuspec
        type bin\win\linkerd.nuspec
    - name: Chocolatey - pack
      # crazy-max/ghaction-chocolatey@v1.2.2
      uses: crazy-max/ghaction-chocolatey@55c9188
      with:
        args: pack bin/win/linkerd.nuspec
    - name: Upload artifact
      # actions/upload-artifact@v1
      uses: actions/upload-artifact@3446296
      with:
        name: choco 
        path: ./linkerd.2.7.1.nupkg
