name: Release
on:
  push:
    tags:
    - "*"
permissions:
  contents: read
env:
  GH_ANNOTATION: true
jobs:
  gh_release:
    name: Create GH release
    timeout-minutes: 30
    if: startsWith(github.ref, 'refs/tags/stable') || startsWith(github.ref, 'refs/tags/edge')
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Set environment variables from scripts
      run: |
        . bin/_tag.sh
        . bin/_release.sh
        echo "TAG=$(CI_FORCE_CLEAN=1 bin/root-tag)" >> $GITHUB_ENV
        extract_release_notes NOTES.md
    - name: Pull CLI binaries
      env:
        DOCKER_MULTIARCH: 1
      run : |
        bin/docker-pull-binaries $TAG
        VERSION=${TAG#"stable-"}
    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@815e45857946b196197a116aa0def711ff7f8ecc
      with:
        draft: false
        prerelease: false
        body_path: NOTES.md
        files: |
          ./target/release/linkerd2-cli-*-darwin*
          ./target/release/linkerd2-cli-*-linux-*
          ./target/release/linkerd2-cli-*-windows.*
