name: Cloud tests
on:
  pull_request:
    paths-ignore:
    - '*.md'
  push:
    paths-ignore:
    - '*.md'
    branches:
    - master
    tags:
    - "*"
jobs:
  cloud_integration_tests:
    name: Cloud integration tests
    runs-on: ubuntu-18.04
    steps:
    - name: Create GKE cluster
      uses: linkerd/linkerd2-action-gcloud@224cd2e
      with:
        cloud_sdk_service_account_key: ${{ secrets.CLOUD_SDK_SERVICE_ACCOUNT_KEY }}
        gcp_project: ${{ secrets.GCP_PROJECT }}
        gcp_zone: ${{ secrets.GCP_ZONE }}
        create: true
        name: testing-eraseme-${{ github.run_id }}
    - name: Run integration tests
      env:
        GITCOOKIE_SH: ${{ secrets.GITCOOKIE_SH }}
      run: echo "************ NOTHING TO DO HERE ***********"
