name: Unit tests
on:
  pull_request:
    paths-ignore:
    - '**.md'
  push:
    paths-ignore:
    - '**.md'
    branches:
    - master
    tags:
    - "*"
jobs:
  go_unit_tests:
    name: Go unit tests
    runs-on: ubuntu-18.04
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
