name: Unit tests
on:
  pull_request:
    paths:
      - '!**.md'
  push:
    branches:
    - master
    tags:
    - "*"
jobs:
  go_unit_tests:
    name: Go unit tests
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
