name: CI

on:
  pull_request: {}
  push:
    branches:
    - master
    tags:
    - "*"

# Jobs by event type and dependencies:

# Unit tests for every master/tag push and PR
#
# validate_go_deps
# go_unit_tests
# go_lint
# js_unit_tests

# Docker build and integration tests for every master/tag push and linkerd org PR
#
# docker_pull
# docker_build
# kind_setup
#   -> kind_integration
#     -> kind_cleanup

# Docker deploy and cloud integration tests for every master/tag push
#
#       -> docker_deploy
#         -> cloud_integration
#           -> cloud_cleanup

jobs:

  hello_world_job:
    runs-on: ubuntu-latest
    name: Create cluster
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build CLI
      run: |
        bin/build-cli-bin

    - name: Create cluster name
      id: cluster-name
      uses: ./.github/actions/cluster-name

    #- name: Create GKE cluster
    #  uses: ./.github/actions/gcloud
    #  with:
    #    cloud_sdk_service_account_key: ${{ secrets.CLOUD_SDK_SERVICE_ACCOUNT_KEY }}
    #    gcp_project: ${{ secrets.GCP_PROJECT }}
    #    gcp_zone: ${{ secrets.GCP_ZONE }}
    #    cluster: ${{ steps.cluster-name.outputs.name }}

  another_job:
    runs-on: ubuntu-latest
    name: Tear down cluster
    needs: hello_world_job
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build CLI
      run: |
        bin/build-cli-bin
        
    - name: Tear down cluster
      env:
        RUN_ID: ${{ github.run_id }}
      run: |
        TAG="$(CI_FORCE_CLEAN=1 bin/root-tag)"
        CLIENT_VERSION=$(target/cli/linux/linkerd version --client --short)
        # validate CLI version matches the repo
        [[ "$TAG" == "$CLIENT_VERSION" ]]
        echo "Installed Linkerd CLI version: $TAG"
        # last part is to distinguish runs on the same sha
        VERSION_STR="$(echo $CLIENT_VERSION | tr -cd '[:alnum:]-')-${RUN_ID: -4}"
        echo $VERSION_STR
        echo "::set-output name=name::testing-$VERSION_STR"