name: CI

on:
  pull_request: {}
  push:
    branches:
    - master
    tags:
    - "*"

# Jobs by event type and dependencies:

# Unit tests for every master/tag push and PR
#
# validate_go_deps
# go_unit_tests
# go_lint
# js_unit_tests

# Docker build and integration tests for every master/tag push and linkerd org PR
#
# docker_pull
# docker_build
# kind_setup
#   -> kind_integration
#     -> kind_cleanup

# Docker deploy and cloud integration tests for every master/tag push
#
#       -> docker_deploy
#         -> cloud_integration
#           -> cloud_cleanup

jobs:

  hello_world_job:
    runs-on: ubuntu-latest
    name: Create cluster
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    #- name: Build CLI
    #  run: |
    #    bin/build-cli-bin

    - name: Foo0
      run: gcloud version

    - name: Foo1
      uses: ./.github/actions/gcloud2
      with:
        cloud_sdk_service_account_key: ${{ secrets.CLOUD_SDK_SERVICE_ACCOUNT_KEY }}
        gcp_project: ${{ secrets.GCP_PROJECT }}
        gcp_zone: ${{ secrets.GCP_ZONE }}
        create: true

    - name: Foo1.1
      run: gcloud version
    #- name: Foo2
    #  uses: ./.github/actions/gcloud
    #  with:
    #    cloud_sdk_service_account_key: ${{ secrets.CLOUD_SDK_SERVICE_ACCOUNT_KEY }}
    #    gcp_project: ${{ secrets.GCP_PROJECT }}
    #    gcp_zone: ${{ secrets.GCP_ZONE }}
    #    destroy: true
