name: CI

on:
  pull_request: {}
  push:
    branches:
    - master
    tags:
    - "*"

# Jobs by event type and dependencies:

# Unit tests for every master/tag push and PR
#
# validate_go_deps
# go_unit_tests
# go_lint
# js_unit_tests

# Docker build and integration tests for every master/tag push and linkerd org PR
#
# docker_pull
# docker_build
# kind_setup
#   -> kind_integration
#     -> kind_cleanup

# Docker deploy and cloud integration tests for every master/tag push
#
#       -> docker_deploy
#         -> cloud_integration
#           -> cloud_cleanup

jobs:

  #
  # Unit tests run for:
  # - every master push
  # - every tag push
  # - every PR
  #

  cloud_integration:
    name: Cloud integration tests
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure gcloud
      uses: ./.github/actions/gcloud
      with:
        cloud_sdk_service_account_key: ${{ secrets.CLOUD_SDK_SERVICE_ACCOUNT_KEY }}
        gcp_project: ${{ secrets.GCP_PROJECT }}
        gcp_zone: ${{ secrets.GCP_ZONE }}
        cluster: testing-git-931bb022-85
    - name: test gcloud
      env:
        VERSION: git-931bb022-85
        CLOUDSDK_CONFIG: /home/runner/work/_temp/_github_home/.config/gcloud
      run: |
        export PATH=/home/runner/work/_temp/_github_home/google-cloud-sdk/bin:$PATH
        sudo chown -R runner /home/runner/work/_temp/_github_home/.config/gcloud
        gcloud container clusters get-credentials testing-$VERSION --zone us-central1-a